[package]
name = "tinybitset"
description = "Generic implementation of small, fixed size, copyable bitsets"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
num-traits = "0.2.17"
